/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "0.5rem",
      },
      boxShadow: {
        card: "0 10px 30px -12px rgba(15, 23, 42, 0.18)",
        button: "0 4px 12px rgba(15, 23, 42, 0.12)",
      },
    },
  },
  plugins: [],
  daisyui: {
    themes: [
      {
        communitypro: {
          primary: "#1f4f7a",
          "primary-content": "#ffffff",
          secondary: "#b88a44",
          "secondary-content": "#ffffff",
          accent: "#2f6b5f",
          "accent-content": "#ffffff",
          neutral: "#10263a",
          "neutral-content": "#e6edf3",
          "base-100": "#f7f8fa",
          "base-200": "#eef2f6",
          "base-300": "#d7e0ea",
          "base-content": "#102235",
          info: "#2b6ea6",
          "info-content": "#ffffff",
          success: "#2f6b5f",
          "success-content": "#ffffff",
          warning: "#c58b2a",
          "warning-content": "#1c1408",
          error: "#b94b4b",
          "error-content": "#ffffff",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
          "--border-btn": "1px",
          "--color-primary": "#1f4f7a",
          "--color-primary-content": "#ffffff",
          "--color-secondary": "#b88a44",
          "--color-secondary-content": "#ffffff",
          "--color-accent": "#2f6b5f",
          "--color-accent-content": "#ffffff",
          "--color-base-100": "#f7f8fa",
          "--color-base-200": "#eef2f6",
          "--color-base-300": "#d7e0ea",
          "--color-base-content": "#102235",
          "--color-neutral": "#10263a",
          "--color-neutral-content": "#e6edf3",
        },
      },
    ],
  },
};
