/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "0.5rem",
      },
      boxShadow: {
        card: "0 10px 30px -12px rgba(15, 23, 42, 0.18)",
        button: "0 4px 12px rgba(15, 23, 42, 0.12)",
      },
    },
  },
  plugins: [],
  daisyui: {
    themes: [
      {
        communitypro: {
          primary: "#08b3f7",
          "primary-content": "#ffffff",
          secondary: "#618e9e",
          "secondary-content": "#ffffff",
          accent: "#10B981",
          "accent-content": "#ffffff",
          neutral: "#161d16",
          "neutral-content": "#e2e9e2",
          "base-100": "#e6f7fe",
          "base-200": "#cef0fd",
          "base-300": "#adbfe4",
          "base-content": "#0f1510",
          info: "#08b3f7",
          "info-content": "#022431",
          success: "#10B981",
          "success-content": "#ffffff",
          warning: "#4e717e",
          "warning-content": "#ffffff",
          error: "#114255",
          "error-content": "#ffffff",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
          "--border-btn": "1px",
          "--color-primary": "#08b3f7",
          "--color-primary-content": "#ffffff",
          "--color-secondary": "#618e9e",
          "--color-secondary-content": "#ffffff",
          "--color-accent": "#99c639",
          "--color-accent-content": "#ffffff",
          "--color-base-100": "#e6f7fe",
          "--color-base-200": "#cef0fd",
          "--color-base-300": "#adbfe4",
          "--color-base-content": "#0f1510",
          "--color-neutral": "#161d16",
          "--color-neutral-content": "#e2e9e2",
        },
      },
    ],
  },
};
